FORMAT: 1A
HOST: http://ehealth.edenlabllc.com/

# eHealth Medical Events API

# Group Medical Events

## Encounter Data Package [/api/patients/{id}/encounter_package]

### Submit Encounter Package [POST]

Using this web service you can submit:

Object| Required| Part of Signed content
-------|---------|------
Visit| 0-1 | false
Encounter| 1-1 |true
Condition| 0-* |true
Observation| 0-* |true
Allergy intolerance| 0-* |true
Immunization| 0-* |true

+ Request Package (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM
    + Attributes (object)
        + include `Submit_Encounter_Package`

+ Response 202 (application/json)
    + Attributes (Response_OK)
        + meta (Response__Meta)
            + code: 202 (number)
        + data (`Job`)

+ Response 404 (application/json)
    + Attributes (Response_Error)
        + meta (Response__Meta)
            + code: 404 (number)
        + error (Response__Error)
            + type: NOT_FOUND (string)
            + message: `Patient not found` (string)

+ Response 422 (application/json)
    + Attributes (Response_Error)
        + meta (Response__Meta)
            + code: 422 (number)
        + error
            + type: unverified (string, required)
            + message: `Property "is_active" has not been defined and the schema does not allow additional properties!` (string, required)


### Get async Job processing details [GET /api/jobs/{id}]
this resource should be used to get the processing status of the async job

+ Parameters
    + id: `NBXk9EyErUZv1RhXgyvgg` (string, required) - request identifier

+ Request (application/json)

    + Headers

            Authorization: Bearer 342432fdsfdsgfdt24535422fgds

+ Response 200 (application/json)
    + Attributes (Response_OK)
        + meta (Response__Meta)
            + code: 200 (number)
        + data (`Job`)

+ Response 203 (application/json)
    + Attributes (Response_OK)
        + meta (Response__Meta)
            + code: 203 (number)
        + data (`Job`)
            + status: `processed`
            + links (array, required, fixed-type)
                + (object)
                    + entity: `visit` (string, required)
                    + href: `/visits/90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required)
                + (object)
                    + entity: `encounter` (string, required)
                    + href: `/encounters/90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required)

+ Response 200 (application/json)
    + Attributes (Response_OK)
        + meta (Response__Meta)
            + code: 200 (number)
        + data (`Job_Error`)

+ Response 404 (application/json)
    + Attributes (Response_Error)
        + meta (Response__Meta)
            + code: 404 (number)
        + error (Response__Error)
            + type: NOT_FOUND (string)
            + message: `Object not found` (string)

### Dummy Encounter [POST]
This chapter describes different examples of Encounters that could be submitted as a signed content in Submit Visit web service.

+ Request Encounter with new Condition (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM
    + Attributes (Encounter_Request)
        
#### Dummy Observation [POST]
Here you can find additional examples of Observations that could be submitted as a part of signed content.

+ Request Oservation (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM
    + Attributes (`Observation_Request`)
    
#### Dummy Condition [POST]
Here you can find additional examples of Conditions that could be submitted as a part of signed content.

+ Request Oservation (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM
    + Attributes (`Condition_Request`)
    
#### Dummy Immunization [POST]
Here you can find additional examples of Immunizations that could be submitted as a part of signed content.

+ Request Oservation (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM
    + Attributes (`Immunization_Request`) 
    
#### Dummy Allergy_Intolerance [POST]
Here you can find additional examples of Allergy_Intolerances that could be submitted as a part of signed content.

+ Request Oservation (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM
    + Attributes (`Allergy_Intolerance_Request`)


### Cancel Encounter Package [GET]
+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes 
        + signed_data: `ew0KICAicGVyaW9kIjogew0KIC...` (string, required) 
    
    

### Cancel Encounter Package Dummy[GET]
+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (`Encounter_Request_Cancel`)    

## Episode of Care [/api/patients/{id}/episodes]

### Create Episode  [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM
    + Attributes (object)
        + include `Episode_Of_Care_Request`

+ Response 200 (application/json)
    

### Get Episode by id[GET /api/patients/{patient_id}/episodes/{id}]
+ Parameters
    + `id` : `70a9e15b-b71b-4caf-8f2e-ff247e8a5677` (string)

    

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (`Episode_Of_Care_Response`)
    

### Get Episodes by search params[GET /api/patients/{id}/episodes]
+ Parameters
    + `id` : `70a9e15b-b71b-4caf-8f2e-ff247e8a5677` (string)
    + `code`: `A20`
    + `page`: 2 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50
    

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (`Episode_Of_Care_Response`)

## Encounter [/api/patient/{id}/episodes/{id}/encounters{?page,page_size}]

### Get Encounters[GET]
+ Parameters
    + `page`: 2 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (`Episode_Of_Care_Response`)
    

## Conditions [/api/patients/{patinet_id}/episodes/{episode_id}/conditions/id]

### Get Conditions by id [GET /api/patients/{patinet_id}/episodes/{episode_id}/conditions/id]
+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (`Condition_Response`)
    

### Get Conditions by Episodes [GET /api/patients/{patinet_id}/episodes/{episode_id}/conditions{?page,page_size}]
+ Parameters
    + `page`: 1 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50
 
    

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (array[`Condition_Response`])
    

### Get Conditions by Encounters [GET /api/patients/{patinet_id}/episodes/{episode_id}/encounters/{encounter_id}/conditions{?page,page_size}]
+ Parameters

    + `page`: 1 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (array[`Condition_Response`])



## Observation [/api/patients/{patient_id}/observation/{id}]

### Get Observation by id[GET /api/patients/{patient_id}/observation/{id}]
+ Parameters

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (`Observation_Response`)
    

### Get Observations by Patients[GET /api/patients/{patient_id}/observations{?page,page_size}]
+ Parameters
    + `page`: 1 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50
+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (array[`Observation_Response`])

### Get Observations by Episodes[GET /api/patients/{patinet_id}/episodes/{episode_id}/observations{?page,page_size}]
+ Parameters
    + `page`: 1 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (array[`Observation_Response`])

### Get Observations by Encounters[GET /api/patients/{id}/episodes/{id}/encounters/{id}/observations{?page,page_size}]
+ Parameters
    + `page`: 1 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (array[`Observation_Response`])

## Allergy Intolerance [/api/patients/{patient_id}/allergy_intolerances/{id}]

### Get Allergy Intolerance by id[GET /api/patients/{patient_id}/allergy_intolerances/{id}]
+ Parameters
 
+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (`Allergy_Intolerance_Response`)

### Get Allergy Intolerances by Patient[GET /api/patients/{patient_id}/allergy_intolerances{?page,page_size}]
+ Parameters
    + `page`: 2 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (array[`Allergy_Intolerance_Response`])
    

### Get Allergy Intolerances by Episodes[GET /api/patients/{patient_id}/episodes/{episode_id}/allergy_intolerances{?page,page_size}]

+ Parameters
    + `page`: 2 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50
    
+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (array[`Allergy_Intolerance_Response`])
    

### Get Allergy Intolerances by Encounters[GET /api/patients/{id}/episodes/{id}/encounters/{id}/allergy_intolerances{?page,page_size}]

+ Parameters
    + `page`: 2 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (application/json)
    + Attributes (array[`Allergy_Intolerance_Response`])

## Immunization [/api/patients/{patient_id}/episodes/{episode_id}/immunizations{?page,page_size}]

### Get Immunization by id[GET /api/patients/{patient_id}/episodes/{episode_id}/immunizations{?page,page_size}]
+ Parameters


+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (array[`Immunization_Response`], fixed-type

### Get Immunizations by Patient[GET /api/patients/{patient_id}/episodes/{episode_id}/immunizations{?page,page_size}]
+ Parameters
    + `page`: 2 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (array[`Immunization_Response`], fixed-type)


### Get Immunizations by Episode[GET /api/patients/{patient_id}/episodes/{episode_id}/immunizations{?page,page_size}]
+ Parameters
    + `page`: 2 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50

+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (array[`Immunization_Response`], fixed-type)

### Get Immunizations by Encounter[GET /api/patients/{patient_id}/episodes/{episode_id}/encounters/{encounter_id}/immunizations{?page,page_size}]
+ Parameters
    + `page`: 2 (number) - Page number.    
    + `page_size`: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50
    
+ Request (application/json)

    + Headers

            Authorization: Bearer mF_9.B5f-4.1JqM

+ Response 200 (array[`Immunization_Response`], fixed-type)
    

# Data Structures

## Responses
### `Response_Collection`
+ meta (Response__Meta, fixed-type)
+ data (array[], fixed-type)
+ paging (`Response__Pagination`, fixed-type)

### `Response_Collection_OK`
+ meta (Response__Meta, fixed-type)
+ data (array[], fixed-type)

### `Response_OK`
+ meta (Response__Meta, fixed-type)
+ data (object, fixed-type)

### `Response__Process_OK`
+ meta (Response__Meta, fixed-type)
+ data (object, fixed-type)
    + affordances (array[Affordance], required) - List of available affordances and their URLs

### `Response_verification_by_phone`
+ `phone_number`: `+380508887700` (string, required)

### `Response_Error`
+ meta (Response__Meta, fixed-type)
    + code: 400 (number)
+ error (Response__Error, fixed-type)

### `Response__Meta`
+ code: 200 (number) - HTTP response code.
+ url: http://example.com/resource (string) - URL to requested resource.
+ type (enum) - Type of data that is located in `data` attribute.
    - object (string) - `data` attribute is a JSON object.
    - list (string) - `data` attribute is a list.
+ `request_id`: `req-adasdoijasdojsda` (string) - [Request ID](http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/request-id). Send it with `X-Request-ID` header.

### `Response__Error`
+ type: type_atom (string) - Atom that represents error type.
+ message: Error description (string) - Human-readable error message. This is for developers, not end-users.

### `Response__Error_DuplicateEntity`
+ type: `object_already_exists` (string) - Atom that represents error type.
+ message: This API already exists (string) - Human-readable error message. This is for developers, not end-users.

### `Response__Error_ValidationFailed`
+ type: validation_failed (string) - type of an error.
+ message: Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors. (string)
+ invalid (array)
    + `entry_type`: `json_data_proprty` (string) - Type of error.
    + entry: $.cvv (string) - JSON Path to an invalid property.
    + rules (array)
        + rule: required (string) - String constant that represents validation rule type. List of all types can be found in [API Manifest](http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors).
        + params (array) - Validation Parameters.

### `Response__Pagination`
+ page_number: 2 (number) - Page number.
+ page_size: 50 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50
+ total_entries: 1000 (number) - Total number of objects in collection.
+ total_pages: 23 (number) - Total number of pages.

### `Affordance`
+ action (string, required) - Affordance action.
+ url (string, required)

### `Reference`
+ identifier (Identifier)

### `Identifier`
+ `type`(Codeable_Concept, required) - Description of identifier
+ `value` : `9183a36b-4d45-4244-9339-63d81cd08d9c` (string, required)- The value that is unique

### `Codeable_Concept`
+ `coding` (array, required, fixed-type)
    + (object)
        + include `Coding`


### `Coding`
+ system : `eHealth` (string, optional)
+ code : `patient` (string, required) - Symbol in syntax defined by the system
+ display : `Patient` (string, optional)- Representation defined by the system

### `Period`
+ start : `2018-08-02T10:45:16.000Z`(string, required) - C? Starting time with inclusive boundary
+ end : `2018-08-02T11:00:00.000Z`(string, optional) - C? End time with inclusive boundary, if not ongoing

### `Quantity`
+ value : `13,5` (number, required)
+ comparator : `>` (string, optional)
+ unit : `mg` (string, required)
+ system : `http:\\snomed` (string, optional)
+ code: `mg` (string, optional)
        

### `Range`
+ low (Quantity, required)
+ high (Quantity, required)

## Episode Of Care

### `Episode_Of_Care_Base`
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required)
+ `type`: `Первинна допомога` (string, required)
+ `status`: `active`
+ name: `Діабет 2018` (string, required)
                    
+ `patient` (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    - display (string)
+ diagnoses_hstr (array, optional, fixed-type)
    + (object)
        + date: `2018-08-02T10:45:16.000Z` (string, required)
        + evidence (Reference, required, fixed-type)
            + identifier (Identifier)
                + type (Codeable_Concept)
                    + coding (array, fixed-type)
                        + (Coding)
                            + code: `encounter` (string)
                            - display (string)
            
        + diagnoses (array, required, fixed-type)
            + (Diagnosis_Referrence_Condition)
            + (Diagnosis_Referrence_Condition_2)
+ managing_organization (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `legal_entity` (string)
                    - display (string)
            
+ period (Period, required)
    - end (string, optional)
+ care_manager (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `employee` (string)
                    - display (string)
                   
            


### `Episode_Of_Care_Request`
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required)
+ `type`: `Первинна допомога` (string, required)
+ `status`: `active`
+ name: `Діабет 2018` (string, required)
            
+ managing_organization (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `legal_entity` (string)
                    - display (string)
            
+ period (Period, required)
    - end (string, optional)
+ care_manager (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `employee` (string)
                    - display (string)
                   
            


### `Episode_Of_Care_Response`
+ include `Episode_Of_Care_Base`

        
##Visit

### `Visit_Body`
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required)
+ period (Period, required)
    + end  : `2018-08-02T10:45:16.000Z` (string, required)

### `Submit_Encounter_Package`

+ `visit` (object, optional, fixed-type)
    + include `Visit_Body`
+ `signed_data` : 'ew0KICAicGVyaW9kIjogew0KIC...' (string, required, fixed-type)




## Diagnosis

### `Diagnosis_New_Condition`
+ condition (Condition_Request, required) - should be filled one of: condition or condition_id
+ `role` (Codeable_Concept, required) - Role that this diagnosis has within the episode of care
    + coding (array, fixed-type)
        + (Coding)
            + `system`: `http://hl7.org/fhir/diagnosis-role`,
            + `code`: `CC`,
            - `display`(string)
    
+ rank: `1` (number, optional) - Ranking of the diagnosis (for each role type)

### `Diagnosis_Referrence_Condition_2`

+ `condition` (Reference, required) - should be filled one of: condition or condition_id
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `condition` (string)
                    - display (string)
+ `code` (Codeable_Concept, required) 
     + coding (array, fixed-type)
        + (Coding)
            + `system`: `ICPC2`,
            + `code`: `D30`,
            - `display` (string)
+ `role` (Codeable_Concept, required) - Role that this diagnosis has within the episode of care
    + coding (array, fixed-type)
        + (Coding)
            + `system`: `??`,
            + `code`: `основний`,
            - `display` (string)
+ rank: `1` (number, optional) - Ranking of the diagnosis (for each role type)

### `Diagnosis_Referrence_Condition`

+ `condition` (Reference, required) - should be filled one of: condition or condition_id
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `condition` (string)
                    - display (string)
+ `code` (Codeable_Concept, required) 
     + coding (array, fixed-type)
        + (Coding)
            + `system`: `ICPC2`,
            + `code`: `A20`,
            - `display` (string)
+ `role` (Codeable_Concept, required) - Role that this diagnosis has within the episode of care
    + coding (array, fixed-type)
        + (Coding)
            + `system`: `??`,
            + `code`: `супутній`,
            - `display` (string)
+ rank: `1` (number, optional) - Ranking of the diagnosis (for each role type)

### `Diagnosis_Response`




## Encouner
### `Encounter_Base` (object)
+ id: `465fb6fe-2dea-4b8a-9ef7-58379d1eaab0` (string, required)
+ `status`: `finised`  (string, required)                 

               
+ `contexts` (array, required, fixed-type)
    + (Reference)
        + identifier (Identifier)
            + type (Codeable_Concept)
                + coding (array, fixed-type)
                    + (Coding)
                        + code: `visit` (string)
                        - display (string)
    + (Reference)
        + identifier (Identifier)
            + type (Codeable_Concept)
                + coding (array, fixed-type)
                    + (Coding)
                        + code: episode (string)
                        - display (string)        

+ class  (Coding, required)
    + system : `http://hl7.org/fhir/v3/ActCode` (string)
    + code: `AMB` (string)
    - display (string)
    
+ type (Codeable_Concept, required)
    + coding (array, fixed-type)
        + (Coding)
            + system: `http://snomed.info/sct` (string)
            + code: `11429006` (string)
            - display (string)
+ incoming_referrals 
+ reasons (array,required)
    + (Codeable_Concept)
        + coding (array, fixed-type)
            + (Coding)
             + system: `??/ICPC2 (string)
             + code: `A02` (string)
             - display (string)
    + (Codeable_Concept)
        + coding (array, fixed-type)
            + (Coding)
                + system: `??/ICPC2 (string)
                + code: `D09` (string)
                - display (string)
        
+ diagnoses (array, required, fixed-type)
    + (`Diagnosis_Referrence_Condition`)
        
        
+ actions (array, required, fixed-type)
    + (Codeable_Concept)
        + coding (array, fixed-type)
            + (Coding)
             + system: `??/ICPC2 (string)
             + code: `T47` (string)
             - display (string)
    + (Codeable_Concept)
        + coding (array, fixed-type)
            + (Coding)
             + system: `??/ICPC2 (string)
             + code: `T50` (string)
             - display (string)
+ division (Reference, required, fixed-type)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `division` (string)
                    - display (string)


### `Encounter_Request` 
+ encounter (`Encounter_Base`, required, fixed-type)
+ conditions (array, optional, fixed-type)
    + (`Condition_Request`)
    + (`Condition_Request_2`)
+ observations (array, optional, fixed-type)
    + (`Observation_Request`)    
+ `allergy_intolerances` (array[`Allergy_Intolerance_Request`], optional, fixed-type)
+ immunizations (array[`Immunization_Request`], optional, fixed-type)


### `Encounter_Request_Cancel`
+ encounters (array, required, fixed-type)
    + (`Encounter_Base`)
        + status: `entered-in-error` (string)
+ conditions (array, optional, fixed-type)
    + (`Condition_Request`)
        + status: `entered-in-error` (string)   
    + (`Condition_Request_2`)
+ observations (array, optional, fixed-type)
    + (`Observation_Request`)
        + status: `entered-in-error` (string)
+ `allergy_intolerances` (array[`Allergy_Intolerance_Request`], optional, fixed-type)
+ immunizations (array[`Immunization_Request`], optional, fixed-type)
+ `explanatory_letter`: `Я, Шевченко Наталія Олександріна, 20.07.2018 здійснила механічну помилку при внесенні обстеження до системи. ` (string, required)    
+ `cancel_reason` (Codeable_Concept, required)
    + coding (array, fixed-type)
        + (Coding)
            + system: `eHealth` (string)
            + code: `misspelling` (string) \\ wrong_patient, misspelling
            - display (string)

###  `Encounter_Response`
+ include `Encounter_Base`

## Condition
### `Condition_Request`
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required)

+ `context` (Reference, required)
     + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `encounter` (string)
                    - display (string)
+ code (Codeable_Concept, required)
    + coding (array, fixed-type)
        + (Coding)
            + system: `??/ICPC2 (string)
            + code: `A89` (string)
            - display (string)
+ clinical_status: `active` (string, required)
+ verification_status: `provisional` (string, required)
+ severity(Codeable_Concept, optional)
    + coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `55604002` (string)
            - display (string)
    
+ body_sites (array, optional, fixed-type)
    + (Codeable_Concept)
        + coding (array, fixed-type)
            + (Coding)
                + system: ` http://snomed.info/sct` (string)
                + code: `181414000` (string)
                - display (string)   
    
+ onset_date: `2018-08-02` (string, required)
+ stage (object, optional)
    + summary (Codeable_Concept, required)
        + coding (array, fixed-type)
            + (Coding)
                + system: ` http://snomed.info/sct` (string)
                + code: `14803004` (string)
                - display (string)
+ evidences
    + code (array, optional, fixed-type)
        + (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + system: ` http://snomed.info/sct` (string)
                    + code: `169068008` (string)
                    - display (string)
    + detail (array, optional, fixed-type)
        + (Reference)
            + identifier (Identifier)
                + type (Codeable_Concept)
                    + coding (array, fixed-type)
                        + (Coding)
                            + code: `observation` (string)
                            - display (string)
        


### `Condition_Request_2`
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required)

+ `context` (Reference, required)
     + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `encounter` (string)
                    - display (string)
+ code (Codeable_Concept, required)
    + coding (array, fixed-type)
        + (Coding)
            + system: `??/ICPC2 (string)
            + code: `K87` (string)
            - display (string)
+ clinical_status: `active` (string, required)
+ verification_status: `provisional` (string, required)
+ severity (Codeable_Concept, optional)
    + coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `55604002` (string)
            - display (string)
    
+ body_sites (array, optional, fixed-type)
    + (Codeable_Concept)
        + coding (array, fixed-type)
            + (Coding)
                + system: ` http://snomed.info/sct` (string)
                + code: `181414000` (string)
                - display (string)   
    
+ onset_date: `2018-08-02` (string, required)
+ stage (object, optional)
    + summary (Codeable_Concept, required)
        + coding (array, fixed-type)
            + (Coding)
                + system: ` http://snomed.info/sct` (string)
                + code: `14803004` (string)
                - display (string)
+ evidences
    + code (array, optional, fixed-type)
        + (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + system: ` http://snomed.info/sct` (string)
                    + code: `169068008` (string)
                    - display (string)
    + detail (array, optional, fixed-type)
        + (Reference)
            + identifier (Identifier)
                + type (Codeable_Concept)
                    + coding (array, fixed-type)
                        + (Coding)
                            + code: `observation` (string)
                            - display (string)
        


### `Condition_Response`
+ id: `6fe6d880-f100-4e39-a278-1d14eb8472ef` (string, required)
+ `patient` (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    - display (string)
+ `context` (Reference, required)
     + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `encounter` (string)
                    - display (string)
+ code (Codeable_Concept, required)
    + coding (array, fixed-type)
        + (Coding)
            + system: `ICPC2/Condition` (string)
            + code: `K86` (string)
            + display: `Гіпертонія неускладнена` (string)
+ clinical_status: `active` (string, required)
+ verification_status: `provisional` (string, required)
+ severity (Codeable_Concept, optional)
    + coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `24484000` (string)
            + display: `Severe` (string)
    
+ body_sites (array, optional)
    + (Codeable_Concept)
        + coding (array, fixed-type)
            + (Coding)
             + system: ` http://snomed.info/sct` (string)
             + code: `181414000` (string)
             + display: `Kidney` (string)   
    
+ onset_date: `2018-08-02` (string, required)
+ stage (object, optional)
    + summary (Codeable_Concept, required)
        + coding (array, fixed-type)
            + (Coding)
                + system: ` http://snomed.info/sct` (string)
                + code: `14803004` (string)
                + display: `Temporary` (string)
+ evidences
    + code (array, optional)
        + (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + system: ` http://snomed.info/sct` (string)
                    + code: `169068008` (string)
                    + display: `CT of neck` (string)
    + detail (array, optional, fixed-type)
        + (Reference)
            + identifier (Identifier)
                + type (Codeable_Concept)
                    + coding (array, fixed-type)
                        + (Coding)
                            + code: `observation` (string)
                            - display (string)
        




## Observation

### `Observation_Request`
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required)
+ status: `valid` (string, required)
+ `context` (Reference, required)
     + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `encounter` (string)
                    - display (string)
+ based_on (Reference, optional)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `referral` (string)
                    - display (string)

+ category (Codeable_Concept, required)
    + coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `vital_signs` (string)
            - display (string)

+ code (Codeable_Concept, required)
    + coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `10569-2` (string)
            - display (string)

- One Of
    + effective_date_time: `2018-08-02` (string, optional)
    + effective_period (Period, optional, fixed-type)
+ issued: `2018-08-02T10:45:16.000Z` (string, required)
+ performer (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `employee` (string)
                    - display (string)

+ interpretation (Codeable_Concept, optional)
    + coding (array, fixed-type)
        + (Coding)
            + system: `http://hl7.org/fhir/v2/0078` (string)
            + code: `L` (string)
            - display (string)
    
+ comment: `Some comment` (string, optional)
+ body_side: 
     + coding (array, fixed-type)
        + (Coding)
            + system: `http://hl7.org/fhir/v2/0078` (string)
            + code: `1341001:272741003=7771000` (string)
            - display (string)

+ method (Codeable_Concept, optional)
    + coding (array, fixed-type)
        + (Coding)
            + system: `http://hl7.org/fhir/v2/0078` (string)
            + code: `255459008` (string)
            - display (string)

- One Of
    + value_quantity (Quantity, required)
    + value_codeable_concept (Codeable_Concept, required)
    + value_sampled_data (object, required)
        + origin (number, optional) //SimpleQuantity Zero value and units
        + period (number, optional) // decimal Number of milliseconds between samples
        + factor (number, optional) // decimal Multiply data by this before adding to origin
        + lowerLimit (number, optional)// decimal Lower limit of detection
        + upperLimit (number, optional) // Σ 0..1 decimal Upper limit of detection
        + dimensions (number, optional) // positiveInt Number of sample points at each time point
        + data (string, required) // Decimal values with spaces, or "E" | "U" | "L"
    + value_string (string, required)
    + value_boolean (boolean, required)
    + value_range (Range, required, fixed-type)
    + value_ratio (object, required)//Need an example 
        + numerator (Quantity, required)
        + denominator (Quantity, required)
    + value_time (string, required)
    + value_date_time (string, required)
    + value_period (Period, required)
+ reference_range (array, optional, fixed-type)
    + (object)
        + low (Quantity, optional)
        + high (Quantity, optional)
            + value: `27,5` (number, required)
            + comparator: `<` (string, required)
        + type (Codeable_Concept, optional)
            +  coding (array, fixed-type)
                + (Coding)
                    + system: ` http://snomed.info/sct` (string)
                    + code: `normal` (string)
                    - display (string)    
        + applies_to (Codeable_Concept, optional)
            +  coding (array, fixed-type)
                + (Coding)
                    + system: ` http://snomed.info/sct` (string)
                    + code: `male` (string)
                    - display (string) 
        + age (Range, optional)
            + low (Quantity, optional)
                + value : `18` (number, required)
                + comparator : `>` (string, optional)
                + unit : `years` (string, optinal)
                - system  (string, optional)
                - code (string, optional)
            + high (Quantity, optional)
                + value : `35` (number, required)
                + comparator : `<` (string, optional)
                + unit : `years` (string, optinal)
                - system (string, optional)
                - code (string, optional)
        + text: `Some text` (string, optional)
+ component (array, optional, fixed-type)
    + (object)
        + code (Codeable_Concept, required)
        - One Of
            + value_quantity (Quantity, required)
            + value_codeable_concept (Codeable_Concept, required)
            + value_sampled_data (object, required)
                + origin (number, optional) //SimpleQuantity Zero value and units
                + period (number, optional) // decimal Number of milliseconds between samples
                + factor (number, optional) // decimal Multiply data by this before adding to origin
                + lowerLimit (number, optional)// decimal Lower limit of detection
                + upperLimit (number, optional) // Σ 0..1 decimal Upper limit of detection
                + dimensions (number, optional) // positiveInt Number of sample points at each time point
                + data (string, required) // Decimal values with spaces, or "E" | "U" | "L"
            + value_string (string, required)
            + value_boolean (boolean, required)
            + value_range (object, required, fixed-type)
                + low (Quantity, required)
                + high (Quantity, required)
            + value_ratio (object, required)//Need an example 
                + numerator (Quantity, required)
                + denominator (Quantity, required)
            + value_time (string, required)
            + value_date_time (string, required)
            + value_period (Period, required)
        + interpretation (Codeable_Concept, optional)
            + coding (array, fixed-type)
                + (Coding)
                    + system: `http://hl7.org/fhir/v2/0078` (string)
                    + code: `L` (string)
                    - display (string)
        + reference_range (array, optional, fixed-type)
            + (object)
                + low (Quantity, optional)
                + high (Quantity, optional)
                    + value: `27,5` (number, required)
                    + comparator: `<` (string, required)
                    + type (Codeable_Concept, optional)
                        +  coding (array, fixed-type)
                            + (Coding)
                                + system: ` http://snomed.info/sct` (string)
                                + code: `normal` (string)
                                - display (string)    
                + applies_to (Codeable_Concept, optional)
                    +  coding (array, fixed-type)
                        + (Coding)
                            + system: ` http://snomed.info/sct` (string)
                            + code: `male` (string)
                            - display (string) 
                + age (Range, optional)
                    + low (Quantity, optional)
                        + value : `18` (number, required)
                        + comparator : `>` (string, optional)
                        + unit : `years` (string, optinal)
                        - system  (string, optional)
                        - code (string, optional)
                    + high (Quantity, optional)
                        + value : `35` (number, required)
                        + comparator : `<` (string, optional)
                        + unit : `years` (string, optinal)
                        - system (string, optional)
                        - code (string, optional)
                
                + text: `Some text` (string, optional)

### `Observation_Response`
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required)
+ status: `valid` (string, required)
+ `context` (Reference, required)
     + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `encounter` (string)
                    - display (string)
+ based_on (Reference, optional)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `referral` (string)
                    - display (string)
+ `patient` (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    - display (string)
+ category (Codeable_Concept, required)
    + coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `vital_signs` (string)
            - display (string)

+ code (Codeable_Concept, required)
    + coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `10569-2` (string)
            + display (string)

- One Of
    + effective_date_time: `2018-08-02` (string, optional)
    + effective_period (Period, optional)
+ issued: `2018-08-02T10:45:16.000Z` (string, required)
+ performer (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `employee` (string)
                    - display (string)

+ interpretation (Codeable_Concept, optional)
    + coding (array, fixed-type)
        + (Coding)
            + system: `http://hl7.org/fhir/v2/0078` (string)
            + code: `L` (string)
            + display: `Low` (string)
    
+ comment: `Some comment` (string, optional)
+ body_side: 
     + coding (array, fixed-type)
        + (Coding)
            + system: `http://hl7.org/fhir/v2/0078` (string)
            + code: `1341001:272741003=7771000` (string)
            - display: `Thoracic nerve` (string)

+ method (Codeable_Concept, optional)
    + coding (array, fixed-type)
        + (Coding)
            + system: `http://hl7.org/fhir/v2/0078` (string)
            + code: `255459008` (string)
            + display: `Total measurement` (string)

- One Of
    + value_quantity (Quantity, required)
    + value_codeable_concept (Codeable_Concept, required)
    + value_sampled_data (object, required)
        + origin (number, optional) //SimpleQuantity Zero value and units
        + period (number, optional) // decimal Number of milliseconds between samples
        + factor (number, optional) // decimal Multiply data by this before adding to origin
        + lowerLimit (number, optional)// decimal Lower limit of detection
        + upperLimit (number, optional) // Σ 0..1 decimal Upper limit of detection
        + dimensions (number, optional) // positiveInt Number of sample points at each time point
        + data (string, required) // Decimal values with spaces, or "E" | "U" | "L"
    + value_string (string, required)
    + value_boolean (boolean, required)
    + value_range (Range, required, fixed-type)
    + value_ratio (object, required)//Need an example 
        + numerator (Quantity, required)
        + denominator (Quantity, required)
    + value_time (string, required)
    + value_date_time (string, required)
    + value_period (Period, required)
+ reference_range (array, optional, fixed-type)
    + (object)
        + low (Quantity, optional)
        + high (Quantity, optional)
            + value: `27,5` (number, required)
            + comparator: `<` (string, required)
        + type (Codeable_Concept, optional)
            +  coding (array, fixed-type)
                + (Coding)
                    + system: ` http://snomed.info/sct` (string)
                    + code: `normal` (string)
                    + display: `Normal` (string)    
        + applies_to (Codeable_Concept, optional)
            +  coding (array, fixed-type)
                + (Coding)
                    + system: ` http://snomed.info/sct` (string)
                    + code: `male` (string)
                    - display (string) 
        + age (Range, optional)
            + low (Quantity, optional)
                + value : `18` (number, required)
                + comparator : `>` (string, optional)
                + unit : `years` (string, optinal)
                - system  (string, optional)
                - code (string, optional)
            + high (Quantity, optional)
                + value : `35` (number, required)
                + comparator : `<` (string, optional)
                + unit : `years` (string, optinal)
                - system (string, optional)
                - code (string, optional)
        + text: `Some text` (string, optional)
+ component (array, optional, fixed-type)
    + (object)
        + code (Codeable_Concept, required)
        - One Of
            + value_quantity (Quantity, required)
            + value_codeable_concept (Codeable_Concept, required)
            + value_sampled_data (object, required)
                + origin (number, optional) //SimpleQuantity Zero value and units
                + period (number, optional) // decimal Number of milliseconds between samples
                + factor (number, optional) // decimal Multiply data by this before adding to origin
                + lowerLimit (number, optional)// decimal Lower limit of detection
                + upperLimit (number, optional) // Σ 0..1 decimal Upper limit of detection
                + dimensions (number, optional) // positiveInt Number of sample points at each time point
                + data (string, required) // Decimal values with spaces, or "E" | "U" | "L"
            + value_string (string, required)
            + value_boolean (boolean, required)
            + value_range (object, required, fixed-type)
                + low (Quantity, required)
                + high (Quantity, required)
            + value_ratio (object, required)//Need an example 
                + numerator (Quantity, required)
                + denominator (Quantity, required)
            + value_time (string, required)
            + value_date_time (string, required)
            + value_period (Period, required)
        + interpretation (Codeable_Concept, optional)
            + coding (array, fixed-type)
                + (Coding)
                    + system: `http://hl7.org/fhir/v2/0078` (string)
                    + code: `L` (string)
                    + display: `Low` (string)
        + reference_range (array, optional, fixed-type)
            + (object)
                + low (Quantity, optional)
                + high (Quantity, optional)
                    + value: `27,5` (number, required)
                    + comparator: `<` (string, required)
                    + type (Codeable_Concept, optional)
                        +  coding (array, fixed-type)
                            + (Coding)
                                + system: ` http://snomed.info/sct` (string)
                                + code: `normal` (string)
                                + display: `normal reference` (string)    
                + applies_to (Codeable_Concept, optional)
                    +  coding (array, fixed-type)
                        + (Coding)
                            + system: ` http://snomed.info/sct` (string)
                            + code: `male` (string)
                            - display (string) 
                + age (Range, optional)
                    + low (Quantity, optional)
                        + value : `18` (number, required)
                        + comparator : `>` (string, optional)
                        + unit : `years` (string, optinal)
                        - system  (string, optional)
                        - code (string, optional)
                    + high (Quantity, optional)
                        + value : `35` (number, required)
                        + comparator : `<` (string, optional)
                        + unit : `years` (string, optinal)
                        - system (string, optional)
                        - code (string, optional)
                
                + text: `Some text` (string, optional)
                
                

## `Immunization`

### `Immunization_Request`
 
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required) 
+ status : `completed` (string, required), //  completed | entered-in-error
+ not_given : `false` (boolean, required), //   Flag for whether immunization was given
+ `vaccine_code` : (Codeable_Concept, required), //   Vaccine product administered
    +  coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `FLUVAX` (string)
            - display (string)

+ encounter : ( Reference, required), // Encounter administered as part of
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `encounter` (string)
                    - display (string)
+ date :  `2018-07-01` (string, required), // Vaccination administration date
+ recorder : ( Reference, required ) // Who recorded the sensitivity
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `employee` (string)
                    - display (string)   
+ asserter : ( Reference, required), // Source of the information about the allergy
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `patient` (string)
                    - display (string)
+ legal_entity : ( Reference, optional), // Where vaccination occurred
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `legal_entity` (string)
                    - display (string)
+ manufacturer : `VacinePro Manufacturer` (string, optional), // Vaccine manufacturer
+ lot_number : `AAJN11K` (string, optional), // Vaccine lot number
+ expiration_date : `2020-07-01` (string, optional), // Vaccine expiration date
+ site : ( Codeable_Concept, optional), // Body site vaccine  was administered
    +  coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `LA` (string)
            - display (string)
+ route : ( Codeable_Concept , optional), // How vaccine entered body
    +  coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `IM` (string)
            - display (string)
+ dose_quantity : ( Quantity, optional), // Amount of vaccine administered
    + value : `18` (number, required)
    - comparator  (string, optional)
    + unit : `mg` (string, optinal)
    + system: `http://unitsofmeasure.org` (string, optional)
    - code (string, optional)
+ practitioner : ( Reference, optional),
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `practitioner` (string)
                    - display (string)
+ explanation : ( object , optional)// Administration/non-administration reasons
    - One Of
        + reasons : ( array, optional, fixed_type), // Why immunization occurred
            + (Codeable_Concept)
               +  coding (array, fixed-type)
                    + (Coding)
                        + system: ` http://snomed.info/sct` (string)
                        + code: `429060002` (string)
                        - display (string) 
        + reason_not_given : ( array, optional, fixed_type), // Why immunization did not occurr
            + (Codeable_Concept)
  ),
+ reactions : (array, optional) // Details of a reaction that follows immunization
    + (object)
        + date : `2018-07-02` (string, optional), // When reaction started
        + detail : ( Reference, optional) , // Additional information on reaction Observation
            + identifier (Identifier)
                + type (Codeable_Concept)
                    + coding (array, fixed-type)
                        + (Coding)
                            + code: `observation` (string)
                            - display (string)
        + reported : `true` (boolean, optional) // Indicates self-reported reaction

+ `vaccination_protocols` : (array, optional, fixed_type)// What protocols was followed
    + (object)
        + dose_sequence : 1 (number, optional), // Dose number within series
        + description : Vaccination Protocol Sequence 1 (string, optional), // Details of vaccine protocol
        + authority : (Codeable_Concept , optional), // Who is responsible for protocol
            +  coding (array, fixed-type)
                    + (Coding)
                        + system: `?` (string)
                        + code: `what` (string)
                        - display (string)
        + series : Vaccination Series 1 (string, optional), // Name of vaccine series
        + series_doses : 2 (number, optional), // Recommended number of doses for immunity
        + target_disease : (array, required)
            + (Codeable_Concept ), //   Disease immunized against
                +  coding (array, fixed-type)
                    + (Coding)
                        + system: `?` (string)
                        + code: `1857005` (string)
                        - display (string)
        + `dose_status` : ( Codeable_Concept, required), // Indicates if dose counts towards immunity
           +  coding (array, fixed-type)
                + (Coding)
                    + system: `?` (string)
                    + code: `count` (string)
                    - display (string)
        + `dose_status_reason` : ( Codeable_Concept,optional) ) // Why dose does (not) count
           +  coding (array, fixed-type)
                + (Coding)
                    + system: `?` (string)
                    + code: `coldchbrk` (string)
                    - display (string)
)

### `Immunization_Response`
 
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required) 
+ status : `completed` (string, required), //  completed | entered-in-error
+ not_given : `false` (boolean, required), //   Flag for whether immunization was given
+ `vaccine_code` : (Codeable_Concept, required), //   Vaccine product administered
    +  coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `FLUVAX` (string)
            + display: `Fluvax (Influenza)` (string)
+ patient : ( Reference, required), // R!  Who was immunized
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
+ recorder : ( Reference, required ) // Who recorded the sensitivity
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `employee` (string)
                    - display (string)   
+ asserter : ( Reference, required), // Source of the information about the allergy
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `patient` (string)
                    - display  (string)
+ encounter : ( Reference, required), // Encounter administered as part of
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `encounter` (string)
                    - display (string)
+ date :  `2018-07-01` (string, required), // Vaccination administration date
  //primarySource : (boolean), // R!  Indicates context the data was recorded in
  //reportOrigin : ( Codeable_Concept ), // Indicates the source of a secondarily reported record
+ legal_entity : ( Reference, optional), // Where vaccination occurred
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `legal_entity` (string)
                    - display (string)
+ manufacturer : `VacinePro Manufacturer` (string, optional), // Vaccine manufacturer
+ lot_number : `AAJN11K` (string, optional), // Vaccine lot number
+ expiration_date : `2020-07-01` (string, optional), // Vaccine expiration date
+ site : ( Codeable_Concept, optional), // Body site vaccine  was administered
    +  coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `LA` (string)
            + display: `left arm` (string)
+ route : ( Codeable_Concept , optional), // How vaccine entered body
    +  coding (array, fixed-type)
        + (Coding)
            + system: ` http://snomed.info/sct` (string)
            + code: `IM` (string)
            + display: `Injection, intramuscular` (string)
+ dose_quantity : ( Quantity, optional), // Amount of vaccine administered
    + value : `18` (number, required)
    - comparator  (string, optional)
    + unit : `mg` (string, optinal)
    + system: `http://unitsofmeasure.org` (string, optional)
    - code (string, optional)
+ practitioner : ( Reference, optional),
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `practitioner` (string)
                    - display (string)
+ explanation : ( object , optional)// Administration/non-administration reasons
    - One Of
        + reasons : ( array, optional, fixed_type), // Why immunization occurred
            + (Codeable_Concept)
               +  coding (array, fixed-type)
                    + (Coding)
                        + system: ` http://snomed.info/sct` (string)
                        + code: `429060002` (string)
                        - display (string) 
        + reason_not_given : ( array, optional, fixed_type), // Why immunization did not occurr
            + (Codeable_Concept)
  ),
+ reactions : (array, optional) // Details of a reaction that follows immunization
    + (object)
        + date : `2018-07-02` (string, optional), // When reaction started
        + detail : ( Reference, optional) , // Additional information on reaction Observation
            + identifier (Identifier)
                + type (Codeable_Concept)
                    + coding (array, fixed-type)
                        + (Coding)
                            + code: `observation` (string)
                            - display (string)
        + reported : `true` (boolean, optional) // Indicates self-reported reaction

+ `vaccination_protocols` : (array, optional, fixed_type)// What protocols was followed
    + (object)
        + dose_sequence : 1 (number, optional), // Dose number within series
        + description : Vaccination Protocol Sequence 1 (string, optional), // Details of vaccine protocol
        + authority : (Codeable_Concept , optional), // Who is responsible for protocol
            +  coding (array, fixed-type)
                    + (Coding)
                        + system: `?` (string)
                        + code: `what` (string)
                        - display (string)
        + series : Vaccination Series 1 (string, optional), // Name of vaccine series
        + series_doses : 2 (number, optional), // Recommended number of doses for immunity
        + target_disease : (array, required)
            + (Codeable_Concept ), //   Disease immunized against
                +  coding (array, fixed-type)
                    + (Coding)
                        + system: `?` (string)
                        + code: `1857005` (string)
                        - display (string)
        + `dose_status` : ( Codeable_Concept, required), // Indicates if dose counts towards immunity
           +  coding (array, fixed-type)
                + (Coding)
                    + system: `?` (string)
                    + code: `count` (string)
                    - display (string)
        + `dose_status_reason` : ( Codeable_Concept,optional) ) // Why dose does (not) count
           +  coding (array, fixed-type)
                + (Coding)
                    + system: `?` (string)
                    + code: `coldchbrk` (string)
                    + display: `Cold chain break` (string)
)


## `Allergy_Intolerance`
### `Allergy_Intolerance_Request`
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required) 
+ clinical_status : `active` (string, required), // C? active | inactive | resolved
+ verification_status : `confirmed` (string, required), // C? R!  unconfirmed | confirmed | refuted | entered-in-error
+ type : `allergy` (string, required), // allergy | intolerance - Underlying mechanism (if known)
+ category : `food`(string, required), // food | medication | environment | biologic
+ criticality : `low`(string, required), // low | high | unable-to-assess
+ context: (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `encounter` (string)
                    - display (string)
+ code : ( Codeable_Concept, required ), // Code that identifies the allergy or intolerance
    +  coding (array, fixed-type)
        + (Coding)
            + system: `?` (string)
            + code: `227493005` (string)

+ onset_date_time : `2000-06-12` (string, required)
+ asserted_date: `2018-08-12` (string, required)
+ recorder : ( Reference, required ) // Who recorded the sensitivity
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `employee` (string)
                    - display (string)   
+ asserter : ( Reference, required), // Source of the information about the allergy
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `patient` (string)
                    - display (string)
+ last_occurrence : `2017-12-12` (string, optional) , // Date(/time) of last known occurrence of a reaction


### `Allergy_Intolerance_Response`
+ id: `90a9e15b-b71b-4caf-8f2e-ff247e8a5600` (string, required) 
+ clinical_status : `active` (string, required), // C? active | inactive | resolved
+ verification_status : `confirmed` (string, required), // C? R!  unconfirmed | confirmed | refuted | entered-in-error
+ type : `allergy` (string, required), // allergy | intolerance - Underlying mechanism (if known)
+ category : `food`(string, required), // food | medication | environment | biologic
+ criticality : `low`(string, required), // low | high | unable-to-assess
+ context: (Reference, required)
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `encounter` (string)
                    - display (string)
+ code : ( Codeable_Concept, required ), // Code that identifies the allergy or intolerance
    +  coding (array, fixed-type)
        + (Coding)
            + system: `?` (string)
            + code: `227493005` (string)
            + display: `Cashew nuts` (string)    
+ patient : ( Reference, required), // R!  Who the sensitivity is for
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    - display (string)
+ onset_date_time : `2000-06-12` (string, required)
+ asserted_date: `2018-08-12` (string, required)
+ recorder : ( Reference, required ) // Who recorded the sensitivity
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `employee` (string)
                    - display (string)   
+ asserter : ( Reference, required), // Source of the information about the allergy
    + identifier (Identifier)
        + type (Codeable_Concept)
            + coding (array, fixed-type)
                + (Coding)
                    + code: `patient` (string)
                    - display (string)
+ last_occurrence : `2017-12-12` (string, optional) , // Date(/time) of last known occurrence of a reaction



### Job
+ status: `processing` (string, required) - status of request processing.
+ eta: `2018-08-02T10:45:16.000Z` (string, optional) - estimated time of arrival
+ links (array, required, fixed-type)
    + (object)
        + include `Link`

### Job_Error
+ status: `error` (string, required) - status of request processing.
+ links (array, required, fixed-type)
    + (object)
        + include `Link`
+ errors (array, optional, fixed-type)
    + (object)
        + include `Error`

### Error
+ code: 422 (string, required)
+ type: type_atom (string, required) - Atom that represents error type.
+ message: Error description (string, required) - Human-readable error message. This is for developers, not end-users.


### Link
+ entity: `job` (string, required) - name of the entity that link follows to
+ href: `/Jobs/NBXk9EyErUZv1RhXgyvgg` (string, required) - link to entity